# docker-compose.yml
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=discord_bot_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=discord_bot_db
    ports:
      - "8000:8000"
    networks:
      - app-network

  discord-bot:
    build:
      context: ./discord-bot
    container_name: discord-bot
    restart: always
    depends_on:
      - mongodb
      - backend
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URI=mongodb://mongodb:27017/discord_bot_db
    env_file:
      - .env
    networks:
      - app-network

  js-website:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" # Exposing nginx on port 3000
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
